// Copyright 2025-2026 Matrix Origin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math"
	"strings"
	"time"
	"unicode"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// UDFWorkerTopology describes the logical placement contract of a Python UDF
// worker. The current Operator implementation supports paired workers in the
// CN Pod only. The other values remain part of the typed API so that an
// unsupported request is rejected deterministically rather than silently
// rendered as a different topology.
type UDFWorkerTopology string

const (
	UDFWorkerTopologyDisabled UDFWorkerTopology = "disabled"
	UDFWorkerTopologyPaired   UDFWorkerTopology = "paired"
	UDFWorkerTopologyPool     UDFWorkerTopology = "pool"
)

// UDFWorkerLauncher identifies the process boundary used by the worker.
type UDFWorkerLauncher string

const (
	UDFWorkerLauncherPythonImage UDFWorkerLauncher = "python-image"
	UDFWorkerLauncherMOService   UDFWorkerLauncher = "mo-service"
)

const (
	// ContainerUDFWorker is the current worker container name. Keep the
	// historical python-udf value out of the new rendered Pod so the old demo
	// cannot be mistaken for the current worker contract.
	ContainerUDFWorker            = "udf-worker"
	ContainerUDFWorkerDefaultPort = 50051

	// UDFWorkerEnabledLabel is deliberately controller-owned. CNPool/CNClaim
	// use it to prevent a Python-enabled Pod from crossing claim owners without
	// a new Pod UID and a new CN/Gateway/worker process.
	UDFWorkerEnabledLabel = "matrixorigin.io/udf-worker-enabled"
	UDFWorkerEnabledValue = "true"
	// UDFWorkerStatusAnno is written by the CN store controller after querying
	// the CN-local Python runtime. It is intentionally bounded and tied to the
	// current Pod UID and policy generation.
	UDFWorkerStatusAnno = "matrixorigin.io/udf-worker-status"
	// UDFWorkerGenerationAnno is copied into each CN Pod template. It binds a
	// capability observation to the generation actually rendered into that Pod;
	// the CN store must not stamp the desired generation onto an old Pod.
	UDFWorkerGenerationAnno = "matrixorigin.io/udf-worker-generation"

	// The direct Python image is built with the unprivileged `mo` account. The
	// Operator repeats its numeric identity in the Pod security context because
	// Kubernetes cannot prove runAsNonRoot from a non-numeric OCI USER alone.
	// Keeping this in the API contract makes the image and rendered Pod agree.
	UDFWorkerRunAsUser  int64 = 1000
	UDFWorkerRunAsGroup int64 = 1000
)

// These ports are occupied by the CN Pod generated by the current CNSet
// renderer. The six-port range starts at the CN port-base and is allocated by
// MatrixOne's internal service address manager; 6001 is the SQL endpoint and
// 7001 is the metrics endpoint. A same-Pod Worker cannot bind any of them.
// Keep this contract in the API package so admission and restore-time
// validation do not drift between the webhook and controllers.
const (
	CNUDFWorkerReservedSQLPort     int32 = 6001
	CNUDFWorkerReservedPortBase    int32 = 6002
	CNUDFWorkerReservedPortSlots   int32 = 5
	CNUDFWorkerReservedMetricsPort int32 = 7001
)

func IsCNPodPortReservedForUDFWorker(port int32) bool {
	return port == CNUDFWorkerReservedSQLPort ||
		(port >= CNUDFWorkerReservedPortBase && port < CNUDFWorkerReservedPortBase+CNUDFWorkerReservedPortSlots) ||
		port == CNUDFWorkerReservedMetricsPort
}

const (
	UDFWorkerConditionEnabled           = "UDFWorkerEnabled"
	UDFWorkerConditionProvisioned       = "UDFWorkerProvisioned"
	UDFWorkerConditionDependencyReady   = "UDFWorkerDependencyReady"
	UDFWorkerConditionCapabilityReady   = "UDFWorkerCapabilityReady"
	UDFWorkerConditionCapacityReady     = "UDFWorkerCapacityReady"
	UDFWorkerConditionRouteReady        = "UDFWorkerRouteReady"
	UDFWorkerConditionClientConfigReady = "UDFClientConfigReady"
	UDFWorkerConditionDraining          = "UDFWorkerDraining"
	UDFWorkerConditionDegraded          = "UDFWorkerDegraded"

	UDFWorkerStatusErrorQueryUnavailable  = "QUERY_UNAVAILABLE"
	UDFWorkerStatusErrorIdentityMismatch  = "IDENTITY_MISMATCH"
	UDFWorkerStatusErrorPolicyMismatch    = "POLICY_MISMATCH"
	UDFWorkerStatusErrorInvalid           = "INVALID_STATUS"
	UDFWorkerStatusErrorStale             = "STALE_STATUS"
	UDFWorkerStatusReasonQueryUnavailable = "PythonStatusQueryUnavailable"
	UDFWorkerStatusReasonIdentityMismatch = "PythonStatusIdentityMismatch"
	UDFWorkerStatusReasonPolicyMismatch   = "PythonStatusPolicyMismatch"
	UDFWorkerStatusReasonInvalid          = "PythonStatusInvalid"
	UDFWorkerStatusReasonStale            = "PythonStatusStale"
)

// These limits are part of the bounded status contract. They apply before a
// status observation is copied into a Kubernetes Condition or stored in a Pod
// annotation, so a malformed or stale producer cannot turn status refreshes
// into an unbounded control-plane payload.
const (
	UDFWorkerStatusMaxStringBytes     = 1024
	UDFWorkerStatusMaxListItems       = 64
	UDFWorkerStatusMaxListItemBytes   = 256
	UDFWorkerStatusMaxAnnotationBytes = 64 << 10
)

// UDFWorkerPolicy is the single typed policy used at the CNSet boundary. A
// nil policy means disabled. A non-nil policy with Enabled=false is an
// explicit, presence-aware disable and must not create worker resources.
//
// The policy intentionally contains no source code, artifact URI, command,
// args, or arbitrary Pod overlay. Function identity and executable artifact
// ownership belong to MatrixOne's Catalog/runtime contracts.
type UDFWorkerPolicy struct {
	// Enabled is the explicit feature switch. It is not inferred from any
	// image, port, or client setting.
	Enabled bool `json:"enabled,omitempty"`

	// +kubebuilder:validation:Enum=disabled;paired;pool
	Topology UDFWorkerTopology `json:"topology,omitempty"`

	// +kubebuilder:validation:Enum=python-image;mo-service
	Launcher UDFWorkerLauncher `json:"launcher,omitempty"`

	Worker UDFWorkerSpec   `json:"worker,omitempty"`
	Client UDFClientConfig `json:"client,omitempty"`

	// Pool is meaningful only for the future independent worker pool
	// topology. It is retained as typed configuration so current admission can
	// reject it without interpreting replicas as a same-Pod worker count.
	// +optional
	Pool *UDFWorkerPoolSpec `json:"pool,omitempty"`
}

// UDFWorkerSpec contains only structured workload properties controlled by
// the Operator. For the current same-Pod topology, scheduling and service
// account fields must remain empty because the worker shares the CN Pod.
type UDFWorkerSpec struct {
	// Image must be an immutable digest for an enabled policy.
	Image string `json:"image,omitempty"`

	// +kubebuilder:validation:Enum=Always;Never;IfNotPresent
	ImagePullPolicy corev1.PullPolicy `json:"imagePullPolicy,omitempty"`

	// Port is the worker's Pod-local Flight port. The Operator owns the bind
	// address and always renders 127.0.0.1 for same-Pod workers. It cannot use
	// a port occupied by the CN SQL, internal service, or metrics endpoints.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	Port int32 `json:"port,omitempty"`

	Resources corev1.ResourceRequirements `json:"resources,omitempty"`

	// These fields are reserved for an external Worker workload. They are
	// rejected for the current same-Pod implementation.
	NodeSelector       map[string]string   `json:"nodeSelector,omitempty"`
	Tolerations        []corev1.Toleration `json:"tolerations,omitempty"`
	ServiceAccountName string              `json:"serviceAccountName,omitempty"`

	UpdateStrategy UDFWorkerUpdateStrategy `json:"updateStrategy,omitempty"`
	MOService      *UDFWorkerMOServiceSpec `json:"moService,omitempty"`
}

type UDFWorkerUpdateStrategy struct {
	// DrainTimeout is used by the future external route owner. Same-Pod
	// workers are drained with the CNSet Pod lifecycle.
	// +optional
	DrainTimeout *metav1.Duration `json:"drainTimeout,omitempty"`
}

type UDFWorkerMOServiceSpec struct {
	// Path and Python are consumed by the future external mo-service launcher.
	// UUID and address are generated from workload identity and are never
	// accepted from the user.
	Path   string `json:"path,omitempty"`
	Python string `json:"python,omitempty"`
}

type UDFClientConfig struct {
	AllowUnisolated bool `json:"allowUnisolated,omitempty"`

	MaxBatchBytes            int64 `json:"maxBatchBytes,omitempty"`
	MaxBatchRows             int64 `json:"maxBatchRows,omitempty"`
	MaxInvocationRows        int64 `json:"maxInvocationRows,omitempty"`
	MaxInvocationResultBytes int64 `json:"maxInvocationResultBytes,omitempty"`
	MaxActiveInvocations     int   `json:"maxActiveInvocations,omitempty"`

	// A nil or zero timeout means the CN runtime default. A positive value is
	// bounded by the current runtime contract.
	// +optional
	RequestTimeout *metav1.Duration `json:"requestTimeout,omitempty"`

	MaxTerminalEntries int64 `json:"maxTerminalEntries,omitempty"`
	MaxTerminalBytes   int64 `json:"maxTerminalBytes,omitempty"`
	// +optional
	TerminalRecordTTL *metav1.Duration `json:"terminalRecordTTL,omitempty"`
}

type UDFWorkerPoolSpec struct {
	Replicas int32 `json:"replicas,omitempty"`
}

// UDFWorkerStatus is intentionally bounded. It contains no source, input,
// secret, log, or invocation identifier.
type UDFWorkerStatus struct {
	Topology       UDFWorkerTopology  `json:"topology,omitempty"`
	Generation     string             `json:"generation,omitempty"`
	DesiredWorkers int32              `json:"desiredWorkers,omitempty"`
	ReadyWorkers   int32              `json:"readyWorkers,omitempty"`
	Conditions     []metav1.Condition `json:"conditions,omitempty"`
}

// UDFWorkerPodStatus is the bounded per-CN observation exchanged between the
// CN query service and the Operator. It contains capability metadata only;
// it must never contain source, artifact locations, secrets, or invocation
// identifiers. PodUID and Generation fence observations from a previous Pod
// or policy revision.
type UDFWorkerPodStatus struct {
	PodUID                     string   `json:"podUID,omitempty"`
	CNUUID                     string   `json:"cnUUID,omitempty"`
	Generation                 string   `json:"generation,omitempty"`
	Ready                      bool     `json:"ready,omitempty"`
	ErrorClass                 string   `json:"errorClass,omitempty"`
	Reason                     string   `json:"reason,omitempty"`
	ProtocolVersion            int32    `json:"protocolVersion,omitempty"`
	ABIContract                string   `json:"abiContract,omitempty"`
	AdapterVersion             string   `json:"adapterVersion,omitempty"`
	SDKVersion                 string   `json:"sdkVersion,omitempty"`
	DefinitionSchemaVersion    int32    `json:"definitionSchemaVersion,omitempty"`
	PlanContractVersion        int32    `json:"planContractVersion,omitempty"`
	TypeDescriptorContract     string   `json:"typeDescriptorContract,omitempty"`
	TimezoneDatabaseVersion    string   `json:"timezoneDatabaseVersion,omitempty"`
	WindowBatches              int32    `json:"windowBatches,omitempty"`
	CumulativeAck              bool     `json:"cumulativeAck,omitempty"`
	MaxExecutionFrameBytes     int64    `json:"maxExecutionFrameBytes,omitempty"`
	MaxHandlerProcesses        int32    `json:"maxHandlerProcesses,omitempty"`
	MaxAccountHandlerProcesses int32    `json:"maxAccountHandlerProcesses,omitempty"`
	MaxOwnerHandlerProcesses   int32    `json:"maxOwnerHandlerProcesses,omitempty"`
	LeaseEpoch                 uint64   `json:"leaseEpoch,omitempty"`
	Modes                      []string `json:"modes,omitempty"`
	NullPolicies               []string `json:"nullPolicies,omitempty"`
	// ObservedAt is set by the CN store status bridge. CNSet accepts a Ready
	// observation only while it is within the controller's bounded freshness
	// window; it is not a durable liveness claim.
	ObservedAt metav1.Time `json:"observedAt,omitempty"`
}

// IsValidUDFRuntimeErrorClass recognizes only errors produced by MO's Python
// runtime status protocol. Controller observation failures are a separate set.
func IsValidUDFRuntimeErrorClass(value string) bool {
	switch value {
	case "", "DISABLED", "NOT_ALLOWED", "UNAVAILABLE", "CONTRACT_MISMATCH", "TIMEOUT", "CLOSED", "INVALID", "INTERNAL":
		return true
	default:
		return false
	}
}

func IsValidUDFWorkerStatusErrorClass(value string) bool {
	if IsValidUDFRuntimeErrorClass(value) {
		return true
	}
	switch value {
	case "",
		UDFWorkerStatusErrorQueryUnavailable,
		UDFWorkerStatusErrorIdentityMismatch,
		UDFWorkerStatusErrorPolicyMismatch,
		UDFWorkerStatusErrorInvalid,
		UDFWorkerStatusErrorStale:
		return true
	default:
		return false
	}
}

// ValidateUDFWorkerPodStatus validates the bounded, controller-facing part of
// a per-Pod Python capability observation. Freshness and Pod/generation fences
// are intentionally checked by the consumer because they require live state.
func ValidateUDFWorkerPodStatus(status *UDFWorkerPodStatus) error {
	if status == nil {
		return fmt.Errorf("nil Python UDF worker status")
	}
	for name, value := range map[string]string{
		"podUID":                  status.PodUID,
		"cnUUID":                  status.CNUUID,
		"generation":              status.Generation,
		"errorClass":              status.ErrorClass,
		"reason":                  status.Reason,
		"abiContract":             status.ABIContract,
		"adapterVersion":          status.AdapterVersion,
		"sdkVersion":              status.SDKVersion,
		"typeDescriptorContract":  status.TypeDescriptorContract,
		"timezoneDatabaseVersion": status.TimezoneDatabaseVersion,
	} {
		if len(value) > UDFWorkerStatusMaxStringBytes {
			return fmt.Errorf("Python UDF worker status %s exceeds %d bytes", name, UDFWorkerStatusMaxStringBytes)
		}
	}
	if !IsValidUDFWorkerStatusErrorClass(status.ErrorClass) {
		return fmt.Errorf("unknown Python UDF worker status error class %q", status.ErrorClass)
	}
	for name, values := range map[string][]string{
		"modes":        status.Modes,
		"nullPolicies": status.NullPolicies,
	} {
		if len(values) > UDFWorkerStatusMaxListItems {
			return fmt.Errorf("Python UDF worker status %s has too many entries", name)
		}
		for _, value := range values {
			if len(value) > UDFWorkerStatusMaxListItemBytes {
				return fmt.Errorf("Python UDF worker status %s entry exceeds %d bytes", name, UDFWorkerStatusMaxListItemBytes)
			}
		}
	}
	return nil
}

// UDFWorkerPolicyGeneration returns the stable identity of the accepted
// worker policy. The same function is used by rendering and status fencing so
// an annotation from an older image, resource, client bound, or port cannot
// make a new policy look ready.
func UDFWorkerPolicyGeneration(policy *UDFWorkerPolicy) string {
	if policy == nil || !policy.Enabled {
		return ""
	}
	canonical := policy.DeepCopy()
	if canonical.Worker.Port == 0 {
		canonical.Worker.Port = ContainerUDFWorkerDefaultPort
	}
	if canonical.Worker.ImagePullPolicy == "" {
		canonical.Worker.ImagePullPolicy = corev1.PullIfNotPresent
	}
	if canonical.Client.RequestTimeout != nil && canonical.Client.RequestTimeout.Duration == 0 {
		canonical.Client.RequestTimeout = nil
	}
	if canonical.Client.TerminalRecordTTL != nil && canonical.Client.TerminalRecordTTL.Duration == 0 {
		canonical.Client.TerminalRecordTTL = nil
	}
	b, err := json.Marshal(canonical)
	if err != nil {
		return ""
	}
	digest := sha256.Sum256(append([]byte("matrixone-python-udf-worker-policy:"), b...))
	return hex.EncodeToString(digest[:])
}

// IsImmutableImageDigest accepts the image identity form used by the
// Kubernetes workload. A tag plus an arbitrary "@sha256:" suffix is not an
// immutable identity; the digest must contain exactly 32 bytes of hex data.
func IsImmutableImageDigest(image string) bool {
	const prefix = "@sha256:"
	if image == "" || strings.IndexFunc(image, unicode.IsSpace) >= 0 {
		return false
	}
	index := strings.LastIndex(image, prefix)
	if index <= 0 || strings.Count(image, prefix) != 1 || len(image)-index-len(prefix) != hex.EncodedLen(sha256DigestBytes) {
		return false
	}
	_, err := hex.DecodeString(image[index+len(prefix):])
	return err == nil
}

const sha256DigestBytes = 32

func (p *UDFWorkerPolicy) IsEnabled() bool {
	return p != nil && p.Enabled
}

func (p *UDFWorkerPolicy) EffectiveTopology() UDFWorkerTopology {
	if !p.IsEnabled() {
		return UDFWorkerTopologyDisabled
	}
	return p.Topology
}

func (p *UDFWorkerPolicy) EffectivePort() int32 {
	if p == nil || p.Worker.Port == 0 {
		return ContainerUDFWorkerDefaultPort
	}
	return p.Worker.Port
}

func (p *UDFWorkerPolicy) EffectiveImagePullPolicy() corev1.PullPolicy {
	if p == nil || p.Worker.ImagePullPolicy == "" {
		return corev1.PullIfNotPresent
	}
	return p.Worker.ImagePullPolicy
}

// Validate performs policy checks independent of an admission field path. The
// webhook adds precise field locations and the controller calls this method
// defensively when a webhook was bypassed during restore or by an older
// controller.
func (p *UDFWorkerPolicy) Validate() error {
	if p == nil {
		return nil
	}
	if p.Topology != "" && p.Topology != UDFWorkerTopologyDisabled &&
		p.Topology != UDFWorkerTopologyPaired && p.Topology != UDFWorkerTopologyPool {
		return fmt.Errorf("UnsupportedUDFWorkerTopology: %q", p.Topology)
	}
	if err := validateUDFClientConfig(&p.Client); err != nil {
		return err
	}
	if !p.Enabled {
		return nil
	}
	if p.Topology == "" {
		return fmt.Errorf("UDFWorkerTopologyRequired")
	}
	if p.Topology != UDFWorkerTopologyPaired && p.Topology != UDFWorkerTopologyPool {
		return fmt.Errorf("UnsupportedUDFWorkerTopology: %q", p.Topology)
	}
	if p.Topology == UDFWorkerTopologyPool {
		return fmt.Errorf("UnsupportedUDFWorkerTopology: pool")
	}
	if p.Pool != nil {
		return fmt.Errorf("UDFWorkerPoolConfigNotAllowedForPaired")
	}
	if p.Launcher == "" {
		return fmt.Errorf("UDFWorkerLauncherRequired")
	}
	if p.Launcher == UDFWorkerLauncherMOService {
		return fmt.Errorf("UnsupportedSamePodMoServiceLauncher")
	}
	if p.Launcher != UDFWorkerLauncherPythonImage {
		return fmt.Errorf("UnsupportedUDFWorkerLauncher: %q", p.Launcher)
	}
	if !IsImmutableImageDigest(p.Worker.Image) {
		return fmt.Errorf("UDFWorkerImageMustUseDigest")
	}
	if p.Worker.Port != 0 && (p.Worker.Port < 1 || p.Worker.Port > 65535) {
		return fmt.Errorf("UDFWorkerPortOutOfRange")
	}
	if IsCNPodPortReservedForUDFWorker(p.EffectivePort()) {
		return fmt.Errorf("UDFWorkerPortConflictsWithCN")
	}
	if p.Worker.ImagePullPolicy != "" &&
		p.Worker.ImagePullPolicy != corev1.PullAlways &&
		p.Worker.ImagePullPolicy != corev1.PullNever &&
		p.Worker.ImagePullPolicy != corev1.PullIfNotPresent {
		return fmt.Errorf("UnsupportedUDFWorkerImagePullPolicy: %q", p.Worker.ImagePullPolicy)
	}
	if !IsFinitePositiveQuantity(p.Worker.Resources.Limits.Cpu()) || !IsFinitePositiveQuantity(p.Worker.Resources.Limits.Memory()) {
		return fmt.Errorf("UDFWorkerResourceLimitsRequired")
	}
	if !IsFiniteNonNegativeQuantity(p.Worker.Resources.Requests.Cpu()) ||
		!IsFiniteNonNegativeQuantity(p.Worker.Resources.Requests.Memory()) {
		return fmt.Errorf("UDFWorkerRequestsOutOfRange")
	}
	if p.Worker.Resources.Requests.Cpu().Cmp(*p.Worker.Resources.Limits.Cpu()) > 0 ||
		p.Worker.Resources.Requests.Memory().Cmp(*p.Worker.Resources.Limits.Memory()) > 0 {
		return fmt.Errorf("UDFWorkerLimitBelowRequest")
	}
	if len(p.Worker.NodeSelector) != 0 || len(p.Worker.Tolerations) != 0 || p.Worker.ServiceAccountName != "" {
		return fmt.Errorf("UnsupportedSamePodWorkerScheduling")
	}
	if p.Worker.UpdateStrategy.DrainTimeout != nil {
		return fmt.Errorf("UnsupportedSamePodWorkerUpdateStrategy")
	}
	if p.Worker.MOService != nil {
		return fmt.Errorf("UnsupportedSamePodMoServiceConfig")
	}
	if !p.Client.AllowUnisolated {
		return fmt.Errorf("UDFWorkerRequiresAllowUnisolated")
	}
	return nil
}

// IsFinitePositiveQuantity is the common resource-limit predicate used by
// both API/controller validation and admission. Sign alone is insufficient:
// resource.Quantity can represent a positive value whose float conversion is
// infinite, which is not a meaningful cgroup limit.
func IsFinitePositiveQuantity(q *resource.Quantity) bool {
	if q == nil || q.Sign() <= 0 {
		return false
	}
	v := q.AsApproximateFloat64()
	return v > 0 && !math.IsInf(v, 0) && !math.IsNaN(v)
}

// IsFiniteNonNegativeQuantity accepts an omitted or zero request, but rejects
// negative, overflowing, NaN-like, and underflowed quantities before they are
// compared with a limit. The Kubernetes API normally validates these fields;
// this helper also protects restore and controller paths that bypass admission.
func IsFiniteNonNegativeQuantity(q *resource.Quantity) bool {
	if q == nil || q.Sign() == 0 {
		return true
	}
	return IsFinitePositiveQuantity(q)
}

func validateUDFClientConfig(c *UDFClientConfig) error {
	if c.MaxBatchBytes < 0 || c.MaxBatchBytes > 1<<30 {
		return fmt.Errorf("UDFClientMaxBatchBytesOutOfRange")
	}
	if c.MaxBatchRows < 0 || c.MaxBatchRows > 1<<30 {
		return fmt.Errorf("UDFClientMaxBatchRowsOutOfRange")
	}
	if c.MaxInvocationRows < 0 || c.MaxInvocationRows > 1<<32 {
		return fmt.Errorf("UDFClientMaxInvocationRowsOutOfRange")
	}
	if c.MaxInvocationResultBytes < 0 || c.MaxInvocationResultBytes > 1<<40 {
		return fmt.Errorf("UDFClientMaxInvocationResultBytesOutOfRange")
	}
	if c.MaxActiveInvocations < 0 || c.MaxActiveInvocations > 1<<20 {
		return fmt.Errorf("UDFClientMaxActiveInvocationsOutOfRange")
	}
	if c.RequestTimeout != nil && (c.RequestTimeout.Duration < 0 || c.RequestTimeout.Duration > time.Hour) {
		return fmt.Errorf("UDFClientRequestTimeoutOutOfRange")
	}
	if c.MaxTerminalEntries < 0 || c.MaxTerminalEntries > 1<<30 {
		return fmt.Errorf("UDFClientMaxTerminalEntriesOutOfRange")
	}
	if c.MaxTerminalBytes < 0 || c.MaxTerminalBytes > 1<<40 {
		return fmt.Errorf("UDFClientMaxTerminalBytesOutOfRange")
	}
	if c.TerminalRecordTTL != nil && c.TerminalRecordTTL.Duration < 0 {
		return fmt.Errorf("UDFClientTerminalRecordTTLOutOfRange")
	}
	return nil
}
